#!/usr/bin/env bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P)"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

DUNST_DIR=$HOME/.config/dunst

# create the config dir if nonexistant
if [ ! -d "$DUNST_DIR" ]; then
  mkdir -p $DUNST_DIR
fi

DUNSTRC_PATH="$DUNST_DIR/dunstrc"

# check if the rc file exists and remove it if it does
if [ -f "$DUNSTRC_PATH" ]; then
  rm -f $DUNSTRC_PATH
fi
# Copy the template file to the user config directory
cp dunstrc.tmpl $DUNSTRC_PATH

# hacky workaround to problem with dunst config not being able to read relative paths.
# find the lines to replace with paths
line_nums=($(awk '/<ICON_PATH_PLACEHOLDER>/ {print FNR}' dunstrc.tmpl))

# sort the file names
icon_names=($(ls $SCRIPTPATH/notif-icons | awk '{ print length, $0} ' | sort -n | cut -d" " -f2-))

# iterate and apply each path to each line in the file
for i in "${!line_nums[@]}"; do
  sed -i "${line_nums[$i]}s|.*|    icon = $SCRIPTPATH/notif-icons/${icon_names[$i]}|" $DUNSTRC_PATH
done

#boot compton or picom if it exists
if [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
elif [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill "$SCRIPTPATH"/background-2.png
fi

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

#boot polybar based on the number of monitors found
if [ -x "$(command -v polybar)" ]; then
  pkill polybar
  monitors="$(polybar -m | sed s/:.*// | tac)"
  while read -r display; do
    MONITOR=$display polybar -c "$SCRIPTPATH/polybar.config" mainbar &> /dev/null &
  done <<< "$monitors"
  exit 0
fi

